/**
 * ExportButton Component
 * BRAND-004: Brand Configuration Dashboard
 * Export brand config to YAML
 * Academia Lendária Design System
 */

import * as React from "react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Icon } from "@/components/ui/icon"
import type { BrandConfiguration, BrandExportYAML } from "@/types/brand"

interface ExportButtonProps {
  config: BrandConfiguration
  variant?: "default" | "outline" | "ghost"
  size?: "default" | "sm" | "lg"
  className?: string
}

function generateYAML(config: BrandConfiguration): string {
  const exportData: BrandExportYAML = {
    version: "1.0",
    exportedAt: new Date().toISOString(),
    brand: {
      name: config.name,
      visualIdentity: {
        logoUrl: config.visualIdentity.logo.url,
        colors: {
          primary: config.visualIdentity.colors.primary.hex,
          secondary: config.visualIdentity.colors.secondary.hex,
          accent: config.visualIdentity.colors.accent.hex,
          ...Object.fromEntries(
            config.visualIdentity.colors.custom.map((c) => [c.name.toLowerCase().replace(/\s+/g, "_"), c.hex])
          ),
        },
        fonts: {
          heading: config.visualIdentity.typography.heading.family,
          body: config.visualIdentity.typography.body.family,
        },
      },
      voice: {
        attributes: config.voice.attributes,
        toneGuidelines: config.voice.toneGuidelines.map((g) => g.text),
      },
      examplesCount: config.examples.examples.length,
    },
  }

  // Simple YAML serialization
  const toYAML = (obj: unknown, indent = 0): string => {
    const spaces = "  ".repeat(indent)

    if (obj === null || obj === undefined) {
      return "null"
    }

    if (typeof obj === "string") {
      // Quote strings that need it
      if (obj.includes("\n") || obj.includes(":") || obj.includes("#")) {
        return `"${obj.replace(/"/g, '\\"')}"`
      }
      return obj
    }

    if (typeof obj === "number" || typeof obj === "boolean") {
      return String(obj)
    }

    if (Array.isArray(obj)) {
      if (obj.length === 0) return "[]"
      return obj.map((item) => `\n${spaces}- ${toYAML(item, indent + 1)}`).join("")
    }

    if (typeof obj === "object") {
      const entries = Object.entries(obj)
      if (entries.length === 0) return "{}"
      return entries
        .map(([key, value]) => {
          if (typeof value === "object" && value !== null && !Array.isArray(value)) {
            return `\n${spaces}${key}:${toYAML(value, indent + 1)}`
          }
          if (Array.isArray(value)) {
            return `\n${spaces}${key}:${toYAML(value, indent + 1)}`
          }
          return `\n${spaces}${key}: ${toYAML(value, indent)}`
        })
        .join("")
    }

    return String(obj)
  }

  return `# Brand Configuration Export
# Generated by Branding OS - Academia Lendária
# ${new Date().toLocaleDateString()}
${toYAML(exportData)}`
}

export function ExportButton({
  config,
  variant = "outline",
  size = "default",
  className,
}: ExportButtonProps) {
  const [isExporting, setIsExporting] = React.useState(false)

  const handleExport = async () => {
    setIsExporting(true)

    try {
      const yaml = generateYAML(config)
      const blob = new Blob([yaml], { type: "text/yaml" })
      const url = URL.createObjectURL(blob)

      const a = document.createElement("a")
      a.href = url
      a.download = `${config.name.toLowerCase().replace(/\s+/g, "-")}-brand-config.yaml`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error("Export failed:", error)
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <Button
      variant={variant}
      size={size}
      onClick={handleExport}
      disabled={isExporting}
      className={cn(className)}
    >
      {isExporting ? (
        <>
          <Icon name="spinner" size="size-4" className="mr-2 animate-spin" />
          Exporting...
        </>
      ) : (
        <>
          <Icon name="download" size="size-4" className="mr-2" />
          Export YAML
        </>
      )}
    </Button>
  )
}
